export const phua = {
    img: '/images/boy.png',
    imgStart: '',
    alt: 'Phua',
    name: 'Phua Yeong Tsann',
    age: '42',
    gender: 'Male',
    bio: 'Phua Yeong Tsann is a Senior Lecturer at School of Computing and Creative Media. He received a BSc in Computer with Education from Universiti Teknologi Malaysia (UTM) and Masters in Computer Science from Universiti Malaya (UM). He has been teaching computing related subjects more than 18 years. Besides that, he was involved in several research projects that were related to environmental impact assessment. He was the system consultants in the projects. Currently he is actively involved in machine learning related research.',
    qualification_acedemic: 'Doctor of Philosophy -PhD in Information Technology, NLP',
    institution_acedemic: 'UTP "Universiti Teknologi PETRONAS"',
    organisation: 'UOWM KDU',
    role: 'Senior Lecturer',
    year: 'OCT 2012',
    level: 'Head of Computing Studies',
    role_admin: 'Supervisor',
    level_admin: 'Head of supervisor',
    start_admin: '2012',
    end_admin: "Present",
    area_expertise: 'Machine Learning with NLP and Deeplearning,',
    book_pub: 'Semantic Extractor Tool: Matlab Results and Evaluation on Sematic Extraction in Sports Video',
    chp_book_pub: 'pp 55-60',
    article_pub: 'None',
    process_pub: 'None',
    mass_media_pub: 'None',
    media_pub: 'None',
    others: 'None',
    title_Areas: 'Machines Learning Translator',
    role_Areas: 'Main Programmer and Main Researcher',
    level_Areas: 'None',
    fromTo_Areas: 'None',
    Source_Areas: 'None',
    title_consult: 'IT Helpdesk Chatbot',
    role_consult: 'Supervisor',
    organisation_consult: 'UOWM KDU',
    fromTo_consult: 'From: Jan 2020 to Dec 2020',
    award: 'National Science Fellowship Scholarship 2000-2002',
    institution_award: 'National Science Fellowship Scholarship',
    level_award: 'None',
    year_award: '2000',
    title_present: 'None',
    organiser_present: 'None',
    level_present: 'None',
    event_present: 'None',
    date_present: 'None',
    describe_link: 'None',
    level_link: 'None',
    duration_link: 'None',
    organisation_link: 'None',
    year_link: 'None',
    activity_contribute: 'Association for Computing Machinery',
    fromTo_contribute: '2015 to present',
    level_contribute: 'None',
    organisation_contribute: 'None',
    role_contribute: 'Professional Member',
    society: 'None',
    end_society: 'None',
    from_society: 'None',
    level_society: 'None',
    name_property: 'None',
    reference_property: 'None',
    type_property: 'None',
    year_property: 'None',
    name_degree: 'Bachelor of Software Engineering (Hons)',
    name_candidates: 'Steven Lee Soon Fatt',
    title_thesis: 'IT Helpdesk chatbot',
    academic_level: 'Degree',
    academic_teach: 'None',
    course_teach: 'Distributed System, Computer Arrchitecture',
    hourContact_teach: '4 hour per week',
    number_student_teach: '24',
    title_consult2: 'A Deep Learning Based Approach with Sequence-to-sequence Generative Model for English to Malay Language Translation,  UOW Malaysia KDU Research Grant',
    role_consult2: 'Researcher',
    fromTo_consult2: '2018',
    organisation_consult2: 'KDU Grant',
    area_expertise2: 'Fundamentals of Deep Learning for Computer Vision',
    area_expertise3: 'Natural Language Processing',
    area_expertise4: 'SAS Certified Base Programmer for SAS 9',
    area_expertise5: 'Data science: Deep Learning in Python',
    qualification_acedemic2: 'Master of Computer Science, Computer Science', 
    institution_acedemic2: 'University of Malay' ,
    qualification_acedemic3: 'Bachelor of Science and Computer with Education, Computer Education, 2nd Upper Class', 
    institution_acedemic3:'Universiti Teknologi Malaysia',

}




